### PR TITLE
Sd/cenum

### PR DESCRIPTION
**Pull request by SimonDanisch**
use CEnum instead of typealiases as long as long as https://github.com/JuliaLang/julia/issues/15728 isn't resolved.
Also fix a few minor problems like typos and the order of declaration and missing `VK_API_VERSION_01`

### CODE REVIEW

**Comment by vchuravy** [comment]
Looks good, but I wouldn't commit `spirv.h`

**Comment by SimonDanisch** [comment]
yeah, didn't realize that the gitignore doesn't handle it yet ;)

**Comment by SimonDanisch** [comment]
Okay, this should be ready to go... Due to the unfamiliar saving behaviour of Atom, it seems that I lost the [doc file generator](https://github.com/JuliaGPU/VulkanCore.jl/blob/sd/highlevel/vulkan_doc.jl), though -.- .

**Comment by vchuravy** [comment]
That's quite annoying since we can't regenerate them quickly anymore.

**Comment by SimonDanisch** [comment]
It is, I still haven't given up hope to find it :D Anyways, it was only ~100 loc, and now I know how to do it...

**Comment by vchuravy** [comment]
Can you squash 5e7c1cd and 5549cc4?

**Comment by SimonDanisch** [comment]
sure thing! (done)

**Pull request merged**
