### PR TITLE
Update to Vulkan 1.3.240

### PR DESCRIPTION
**Pull request by serenity4**
This uses the latest Clang version, which showed no difference in the generated wrapper (tested for the Linux wrapper) before the update to 1.3.240.

I also removed a bunch of const annotations to facilitate tweaking the generator while prototyping.

TODO:
- [x] Remove `dev`ed specification for Clang (see JuliaInterop/Clang.jl#415)
- [x] Test correct wrapping on Vulkan.jl

### CODE REVIEW

**Comment by serenity4** [comment]
It seems like there are a few issues with finding `libvulkan` on MacOS, I don't know if that's a file permission issue or a wrong library name or a missing library include path. [This guide](https://vulkan.lunarg.com/doc/view/1.2.176.1/mac/getting_started.html) (though perhaps a bit outdated) seems to indicate the use of `libvulkan.1.dylib` as library name, but setting this CI had no effect.

EDIT: I just realized it was already captured in #37.

**Comment by serenity4** [comment]
Windows CI timed out during the installation of the SDK, it might be that the .exe requires interaction of some sort, though it used to be working fine before.

**Comment by serenity4** [comment]
Alright, it got me some time (with a distraction under the form of https://github.com/serenity4/VulkanSpec.jl) but this PR is tested and ready now :)

FYI, the Vulkan Video bindings are only for decode operations, which are no longer provisional, and encode operations (which are still provisional) are not included. Therefore it should be in line with our discussion in https://github.com/JuliaGPU/VulkanCore.jl/issues/43.

I may update to v1.3.266 (or whatever will be the latest) soon after this PR, but if that is the case, it's anyways good to make incremental changes.

**Comment by serenity4** [comment]
(@Gnimuc if you have time to review, that would be fantastic, but otherwise it's alright - I am reasonably confident that I can merge this in the current state)

**Review by Gnimuc — APPROVED** [review]
The generator script looks good to me.

**Comment by Gnimuc** [comment]
We may fix the Windows CI in the future though. (The last time I tried, it was still hard to debug the CI environment...)

**Comment by serenity4** [comment]
Thanks! Yep, eventually we should try to get Vulkan to work reliably on all platforms. I've been trying to put the validation layers in Yggdrasil, but it's not an easy one.

**Pull request merged**
