### PR TITLE
WIP compile julia to spir-v

### PR DESCRIPTION
**Pull request by carnaval**
far from done, let's just have this here for now

### CODE REVIEW

**Comment by vchuravy** [comment]
master now contains the wrapper for spir-v

**Comment by jpsamaroo** [comment]
I imagine this should be closed since GPUCompiler.jl now has SPIR-V integration? @vchuravy

**Comment by vchuravy** [comment]
Indeed

**Comment by ToucheSir** [comment]
I don't think GPUCompiler's SPIR-V codegen supports Vulkan? Last I checked it's still pending in LLVM-SPIRV-Translator: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/30, https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/74.

**Comment by jpsamaroo** [comment]
That's fair, although I think this code probably shouldn't live here anyway, since SPIR-V clearly has uses outside of Vulkan.

**Comment by ToucheSir** [comment]
I wish there was a better language-agnostic path for this. e.g. https://github.com/EmbarkStudios/rust-gpu has to define its own backend for SPIR-V.

**Pull request closed without merging**
